# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 743e0ea21b5a011d2271b17d30a965ebc4f79436c11e175b38ba6d08d3b03e2a91f492942e4e001696c2190ae480b582ccf4090b905a765f95e5a763dcfd3dce

test:
  secret_key_base: 0cf6552c7f8bf5dd7cb1370f7cde2539b0d6529baf7e37b445ce0cccb749b4f482d978c4ee13ab1904a3f4d069b477fc5064a59d5da3097c85c978d200408e71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
