image: ruby:2.4.1

services:
  - postgres:latest

variables:
  POSTGRES_DB: wulin_app_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ''

before_script:
  - apt-get update -qy
  - apt-get install -qy nodejs
  - apt-get install -qy libfontconfig1
  - gem install bundler
  - cp spec/wulin_app/config/database.ci.yml spec/wulin_app/config/database.yml
  - rm -rf Gemfile.lock
  - bundle install --path /cache
  - bundle exec rake db:drop || true
  - bundle exec rake db:create db:migrate

test:
  script:
    - bundle exec rubocop
    - bundle exec rspec
    - bundle exec rake assets:precompile
    - bundle exec cucumber
