image: ruby:2.3.1

services:
  - postgres:latest

variables:
  POSTGRES_DB: wulin_app_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ''

before_script:
  - apt-get update -qy
  - apt-get install -qy nodejs
  - apt-get install -qy libfontconfig1
  - export PHANTOM_JS_VERSION="2.1.1"
  - wget -q https://github.com/paladox/phantomjs/archive/v$PHANTOM_JS_VERSION.tar.gz -P /cache/phantomjs/
  - tar xzf /cache/phantomjs/v$PHANTOM_JS_VERSION.tar.gz -C /cache
  - mv /cache/phantomjs-$PHANTOM_JS_VERSION /usr/local/share
  - ln -sf /usr/local/share/phantomjs-$PHANTOM_JS_VERSION/bin/phantomjs /usr/local/bin
  - gem install bundler
  - cp spec/wulin_app/config/database.ci.yml spec/wulin_app/config/database.yml
  - bundle install --path /cache

test:
  script:
    - bundle exec rspec
    - bundle exec cucumber
