image: ruby:2.3.1

stages:
  - test

cache:
  paths:
    - cache/

before_script:
  - apt-get update -qy
  - apt-get install -y nodejs
  - gem install bundler
  - bundle install --path /cache

rspec:
  script:
    - bundle exec rspec
