image: ruby:2.3.1

services:
  - postgres:latest

variables:
  POSTGRES_DB: wulin_app_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ''

before_script:
  - apt-get update -qy
  - apt-get install -qy nodejs
  - apt-get install -qy libfontconfig1
  - export PHANTOM_JS="phantomjs-2.1.1-linux-x86_64"
  - wget -q https://bitbucket.org/ariya/phantomjs/downloads/$PHANTOM_JS.tar.bz2 --referer=https://bitbucket.org -P /cache/
  - tar xjf $PHANTOM_JS.tar.bz2
  - mv $PHANTOM_JS /usr/local/share
  - ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin
  - gem install bundler
  - cp spec/wulin_app/config/database.ci.yml spec/wulin_app/config/database.yml
  - bundle install --path /cache

test:
  script:
    - bundle exec rspec
    - bundle exec cucumber
